import type { OpenApiMetadataEntry } from "../../openapi/metadata";

export const blogOpenApiMetadata: readonly OpenApiMetadataEntry[] = [
  {
    path: "/api/blog/posts",
    method: "get",
    mode: "anonymous",
    capability: "content.manage",
    scope: "blog:read",
  },
  {
    path: "/api/blog/posts",
    method: "post",
    mode: "account",
    capability: "content.manage",
    scope: "blog:write",
  },
  { path: "/api/blog/posts/{postId}", method: "get", mode: "anonymous" },
  {
    path: "/api/blog/posts/{postId}",
    method: "patch",
    mode: "account",
    capability: "content.manage",
    scope: "blog:write",
  },
  {
    path: "/api/blog/posts",
    method: "delete",
    mode: "account",
    capability: "content.manage",
    scope: "blog:manage",
  },
  { path: "/api/blog/categories", method: "get", mode: "anonymous" },
  {
    path: "/api/blog/categories",
    method: "post",
    mode: "account",
    capability: "content.manage",
    scope: "blog:write",
  },
  {
    path: "/api/blog/categories/{categoryId}",
    method: "get",
    mode: "account",
    capability: "content.manage",
    scope: "blog:read",
  },
  {
    path: "/api/blog/categories/{categoryId}",
    method: "patch",
    mode: "account",
    capability: "content.manage",
    scope: "blog:write",
  },
  {
    path: "/api/blog/categories",
    method: "delete",
    mode: "account",
    capability: "content.manage",
    scope: "blog:manage",
  },
  { path: "/api/blog/tags", method: "get", mode: "anonymous" },
  {
    path: "/api/blog/tags",
    method: "post",
    mode: "account",
    capability: "content.manage",
    scope: "blog:write",
  },
  {
    path: "/api/blog/tags/{tagId}",
    method: "get",
    mode: "account",
    capability: "content.manage",
    scope: "blog:read",
  },
  {
    path: "/api/blog/tags/{tagId}",
    method: "patch",
    mode: "account",
    capability: "content.manage",
    scope: "blog:write",
  },
  {
    path: "/api/blog/tags",
    method: "delete",
    mode: "account",
    capability: "content.manage",
    scope: "blog:write",
  },
];
