import {afterAll,beforeEach,describe,expect,it} from "vitest";
import {createContainer} from "@/infrastructure/container";
import {newId} from "@/kernel/ids";
const databaseUrl=process.env.TEST_DATABASE_URL;const suite=databaseUrl?describe:describe.skip;
suite("provider-neutral payout execution",()=>{const app=createContainer(databaseUrl!);
  beforeEach(async()=>{await app.database.query(`truncate table payout_capability.attempts,payout_capability.executions,withdrawal_capability.withdrawals,ledger_capability.withdrawal_reservation_events,ledger_capability.withdrawal_reservations,ledger_capability.entry_settlements,ledger_capability.entries,ledger_capability.purchase_distributions,payment_capability.reconciliation_attempts,payment_capability.provider_events,access_capability.access_grants,entitlement_capability.entitlements,purchase_capability.purchases,payment_capability.payments,listing_capability.listings,identity_capability.account_capabilities,identity_capability.sessions,identity_capability.accounts,kernel.outbox_events,kernel.idempotency_records restart identity cascade`);
    await app.database.query(`update ledger_capability.distribution_policy set initial_balance_state='available',settlement_delay_seconds=0,platform_rate_basis_points=0`);await app.database.query(`update referral_capability.commission_policy set rates_basis_points='{}'`);await app.database.query(`update withdrawal_capability.policy set minimum_amount_minor=1,enabled=true`);});
  afterAll(()=>app.database.close());
  async function setup(destinationReference="normal"){const seller=await app.authentication.register({email:`seller-${newId().slice(0,6)}@example.com`,handle:`sell${newId().slice(0,8)}`,password:"correct-horse-battery"});const buyer=await app.authentication.register({email:`buyer-${newId().slice(0,6)}@example.com`,handle:`buy${newId().slice(0,8)}`,password:"correct-horse-battery"});const listing=await app.listingService.create(seller,{title:"Payout",description:"",priceMinor:"10000",currency:"USD",destination:"https://example.test"});const checkout=await app.legacyProviderCheckout.initiate({buyerId:buyer.id,buyerEmail:buyer.email,listingId:listing.id,providerName:"development",idempotencyKey:newId()});await app.legacyPaymentCompletion.complete({paymentId:checkout.paymentId,correlationId:newId()});await app.purchaseDistribution.process({purchaseId:checkout.purchaseId!,correlationId:newId()});await app.database.query(`update withdrawal_capability.policy set minimum_amount_minor=1`);const withdrawal=await app.withdrawals.request({accountId:seller.id,amountMinor:5000n,currency:"USD",destinationType:"manual",destinationReference:destinationReference,idempotencyKey:newId(),correlationId:newId()});await app.database.query(`insert into identity_capability.account_capabilities(account_id,capability) values($1,'operator')`,[seller.id]);await app.withdrawals.approve(seller.id,withdrawal.id);return {seller,withdrawal};}
  it("submits only approved withdrawals and completes exactly once on verified success",async()=>{const {seller,withdrawal}=await setup();await expect(app.payoutExecution.execute(withdrawal.id,newId())).resolves.toMatchObject({kind:"succeeded"});await expect(app.payoutExecution.execute(withdrawal.id,newId())).resolves.toMatchObject({state:"succeeded"});expect((await app.withdrawalRepository.findById(withdrawal.id))?.state).toBe("completed");expect(await app.payoutExecution.attempts(withdrawal.id)).toHaveLength(1);expect((await app.fundsReservation.summarize(seller.id))[0].completedMinor).toBe(5000n);});
  it("preserves reservation on retryable and permanent failures",async()=>{const retry=await setup("dev:retry");await expect(app.payoutExecution.execute(retry.withdrawal.id,newId())).resolves.toMatchObject({kind:"failed",category:"retryable_technical"});expect((await app.withdrawalRepository.findById(retry.withdrawal.id))?.state).toBe("approved");expect((await app.fundsReservation.summarize(retry.seller.id))[0].reservedMinor).toBe(5000n);await app.database.query(`update payout_capability.executions set next_attempt_at=now()-interval '1 second' where withdrawal_id=$1`,[retry.withdrawal.id]);await expect(app.payoutExecution.execute(retry.withdrawal.id,newId())).resolves.toMatchObject({kind:"failed"});const permanent=await setup("dev:permanent");await expect(app.payoutExecution.execute(permanent.withdrawal.id,newId())).resolves.toMatchObject({kind:"failed",category:"permanent_validation"});expect((await app.fundsReservation.summarize(permanent.seller.id))[0].reservedMinor).toBe(5000n);});
  it("does not blindly retry unknown outcomes and reconciles verified success",async()=>{const {seller,withdrawal}=await setup("dev:unknown");await expect(app.payoutExecution.execute(withdrawal.id,newId())).resolves.toMatchObject({kind:"unknown"});expect((await app.fundsReservation.summarize(seller.id))[0].reservedMinor).toBe(5000n);await expect(app.payoutExecution.execute(withdrawal.id,newId())).resolves.toMatchObject({state:"unknown"});await expect(app.payoutExecution.reconcile(withdrawal.id,newId())).resolves.toMatchObject({kind:"succeeded"});expect((await app.withdrawalRepository.findById(withdrawal.id))?.state).toBe("completed");expect(await app.payoutExecution.attempts(withdrawal.id)).toHaveLength(1);});
  it("converges concurrent execution attempts on one provider submission",async()=>{const {withdrawal}=await setup();const results=await Promise.all([app.payoutExecution.execute(withdrawal.id,newId()),app.payoutExecution.execute(withdrawal.id,newId())]);expect((results as any[]).filter(result=>result?.kind==="succeeded")).toHaveLength(1);expect(await app.payoutExecution.attempts(withdrawal.id)).toHaveLength(1);});
});
