import {afterAll,beforeEach,describe,expect,it} from "vitest";
import {createContainer} from "@/infrastructure/container";
import {newId} from "@/kernel/ids";
const url=process.env.TEST_DATABASE_URL;const suite=url?describe:describe.skip;
suite("wallet-first durable commerce",()=>{const app=createContainer(url!);
  beforeEach(async()=>{await app.database.query(`truncate table wallet_capability.debits,wallet_capability.credits,checkout_capability.checkouts,funding_capability.funding_transactions,ledger_capability.entries,ledger_capability.purchase_distributions,access_capability.access_grants,entitlement_capability.entitlements,purchase_capability.purchases,payment_capability.payments,listing_capability.listings,identity_capability.sessions,identity_capability.accounts,kernel.outbox_events,kernel.idempotency_records restart identity cascade`);});afterAll(()=>app.database.close());
  async function setup(){const seller=await app.authentication.register({email:"wallet.seller@example.com",handle:"walletseller",password:"correct-horse-battery"});const buyer=await app.authentication.register({email:"wallet.buyer@example.com",handle:"walletbuyer",password:"correct-horse-staple",country:"NG"});const listing=await app.listingService.create(seller,{title:"Wallet item",description:"",priceMinor:"1000",currency:"USD",destination:"https://destination.example/item"});return {seller,buyer,listing};}
  it("keeps funding confirmation, wallet credit, availability, checkout, entitlement and distribution as independent durable phases",async()=>{const {seller,buyer,listing}=await setup();const checkout=await app.walletCheckout.initiate({buyerId:buyer.id,listingId:listing.id,idempotencyKey:"buy-1"});expect(checkout.state).toBe("awaiting_funds");expect((await app.wallet.summary(buyer.id)).available.minorAmount).toBe(0n);
    const funding=await app.fundingService.create({accountId:buyer.id,amountMinor:1000n,providerName:"development",idempotencyKey:"fund-1"});await app.fundingInitialization.process(funding.id);const confirmed=await app.fundingVerification.process(funding.id);expect(confirmed?.state).toBe("confirmed");expect((await app.wallet.summary(buyer.id)).available.minorAmount).toBe(0n);expect(await app.entitlements.findByPurchaseId(checkout.purchaseId)).toBeNull();
    await app.walletCredit.process(funding.id);expect((await app.wallet.summary(buyer.id)).pending.minorAmount).toBe(1000n);expect((await app.wallet.summary(buyer.id)).available.minorAmount).toBe(0n);
    await app.walletAvailability.runBatch();expect((await app.wallet.summary(buyer.id)).available.minorAmount).toBe(1000n);expect((await app.checkoutRepository.findById(checkout.id))?.state).toBe("awaiting_funds");
    await app.checkoutPayment.process(checkout.id);expect((await app.checkoutRepository.findById(checkout.id))?.state).toBe("paid");expect((await app.wallet.summary(buyer.id)).available.minorAmount).toBe(0n);expect((await app.purchases.findById(checkout.purchaseId))?.state).toBe("paid");expect(await app.entitlements.findByPurchaseId(checkout.purchaseId)).toBeNull();
    const entitlement=await app.entitlementIssuance.process(checkout.purchaseId);expect(entitlement?.isActive).toBe(true);expect(await app.ledger.findDistributionByPurchaseId(checkout.purchaseId)).toBeNull();const destination=await app.buyerAccess.handoffPurchase(buyer,checkout.purchaseId,"wallet-access");const source=destination.searchParams.get("source")!;const integration=await app.integrations.create(seller.id,"wallet destination",listing.id);const principal=await app.integrations.authenticate(integration.credential);expect(await app.access.verify(source,principal!)).toMatchObject({authorized:true,buyerId:buyer.id,listingId:listing.id});await app.purchaseDistribution.process({purchaseId:checkout.purchaseId,correlationId:newId()});expect((await app.ledger.findDistributionByPurchaseId(checkout.purchaseId))?.gross.currency).toBe("USD");
    await Promise.all([app.checkoutPayment.process(checkout.id),app.checkoutPayment.process(checkout.id),app.entitlementIssuance.process(checkout.purchaseId),app.entitlementIssuance.process(checkout.purchaseId)]);expect((await app.database.query(`select 1 from wallet_capability.debits where checkout_id=$1`,[checkout.id])).rowCount).toBe(1);expect((await app.database.query(`select 1 from entitlement_capability.entitlements where purchase_id=$1`,[checkout.purchaseId])).rowCount).toBe(1);
  });
  it("denies expired entitlements without depending on an expiry worker",async()=>{const e=new (await import("@/modules/entitlement/entitlement")).Entitlement(newId(),newId(),newId(),newId(),new Date(Date.now()-1000));expect(e.isActive).toBe(false);});
});
