services:
  main:
    volumes:
      - ../../config/modules/payment/paystack.yaml:/workspace/config/modules/payment/paystack.yaml:ro
      - ../../config/secrets/payment/paystack.yaml:/workspace/config/secrets/payment/paystack.yaml:ro

